name: ProgrammerCave
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
url: https://programmercave.github.io/
social:
  name: ProgrammerCave
  links: 
    - https://www.facebook.com/programmercave/
    - https://www.instagram.com/programmercave/
    - https://t.me/programmercave
