title: ProgrammerCave
description: Implementation of basic algorithms, data structures in C++ mostly. Stuff related to Computer Science like Operating Systems, Networking. Basic hacking and exploitation stuff and some linux stuff.
keywords: Programming competitive code coding C++ Python C Java Algorithm Data Structure
language: "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

markdown: kramdown
#kramdown:
 # syntax_highlighter_opts:
  #  disable: false
permalink: /blog/:year/:month/:day/:title
plugins_dir:
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

  
comments:
  facebook:
    appid: 389979625280769
    profile_id: programmercave                      # For follow button or profile link
    action: like          # Or recommend
    share: true         # Also add a share button
    layout: button        # Choices: standard, box_count, button_count, button
    show_faces: false
    colorscheme: light         # Or dark
    kid_directed_site: false         # Is your site directed at kids under 13?
    share_link_text: Facebook            # Text for plain-old link
    share_link_title: Share on Facebook   # Share link title text
    #profile_link_text:   Friend on Facebook
    #profile_link_title:  Friend on Facebook  # Profile link title text
    num_posts: 10
    colorscheme: "light"
    order_by: "reverse_time"
  
  
url: https://programmercave0.github.io/
social-network-links:
  #dribbble:
  #email:
  facebook: programmercave
  #flickr:
  github: programmercave0
  instagram: programmercave
  #linkedin:
  #pinterest:
  rss: true # just type anything here for a working RSS icon
  twitter: programmercave
  telegram: true
  #stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  #youtube: # channel/<your_long_string> or user/<user-name>
  #googleplus: # anything in your profile username that comes after plus.google.com/
  
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  reddit: true
  whatsapp: true
  telegram: true

exclude: [vendor]
  
# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

#
# This file contains configuration flags to customize your site
#

#
# Flags below are optional
#

link-col: "##4400ff"



# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-102581341-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitema.xml and your RSS feed


# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/programmercave"

#
# !! You don't need to change any of the configuration flags below !!

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    values:
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts

# Use tags index page and make tags on each post clickable
link-tags: true

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed



# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-minimal
